/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Table,
} from './types';

export namespace Components {
  interface AppRoot {}
  interface HtmlTableGenerator {
    'close': () => void;
    'table'?: Table;
  }
  interface InitGenerator {}
  interface TableForm {
    '_matrix'?: { columns: number, rows: number };
    'table'?: Table;
  }
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLHtmlTableGeneratorElement extends Components.HtmlTableGenerator, HTMLStencilElement {}
  var HTMLHtmlTableGeneratorElement: {
    prototype: HTMLHtmlTableGeneratorElement;
    new (): HTMLHtmlTableGeneratorElement;
  };

  interface HTMLInitGeneratorElement extends Components.InitGenerator, HTMLStencilElement {}
  var HTMLInitGeneratorElement: {
    prototype: HTMLInitGeneratorElement;
    new (): HTMLInitGeneratorElement;
  };

  interface HTMLTableFormElement extends Components.TableForm, HTMLStencilElement {}
  var HTMLTableFormElement: {
    prototype: HTMLTableFormElement;
    new (): HTMLTableFormElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'html-table-generator': HTMLHtmlTableGeneratorElement;
    'init-generator': HTMLInitGeneratorElement;
    'table-form': HTMLTableFormElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface HtmlTableGenerator {
    'close'?: () => void;
    'table'?: Table;
  }
  interface InitGenerator {
    'onSetMatrix'?: (event: CustomEvent<any>) => void;
  }
  interface TableForm {
    '_matrix'?: { columns: number, rows: number };
    'onEditTable'?: (event: CustomEvent<any>) => void;
    'table'?: Table;
  }

  interface IntrinsicElements {
    'app-root': AppRoot;
    'html-table-generator': HtmlTableGenerator;
    'init-generator': InitGenerator;
    'table-form': TableForm;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'html-table-generator': LocalJSX.HtmlTableGenerator & JSXBase.HTMLAttributes<HTMLHtmlTableGeneratorElement>;
      'init-generator': LocalJSX.InitGenerator & JSXBase.HTMLAttributes<HTMLInitGeneratorElement>;
      'table-form': LocalJSX.TableForm & JSXBase.HTMLAttributes<HTMLTableFormElement>;
    }
  }
}


